Repository htw-pv3/weather-data, pull requests merged in 2020-05, with the labels that each got.

#6 reworked metadata wr1
  helfenbein_kilian_metadata/einleuchtend_wrdata_2015_wr1_v140_KH.json
Labels: review

#9 some minor corrections
  helfenbein_kilian_metadata/htw_wetter_weatherdata_2015_v140_KH.json
Labels: documentation, help wanted, review

#8 edited the types of resources in wr5 , added missing resources, #3
  helfenbein_kilian_metadata/einleuchtend_wrdata_2015_wr5_v140_KH.json
Labels: enhancement, help wanted

#7 Reworked names and types of resources in wr4. Added 3 missing collumns #3
  helfenbein_kilian_metadata/einleuchtend_wrdata_2015_wr4_v140_KH.json
Labels: enhancement, review

#12 Release/metadata 0.0.1
  metadata/db_log.json
  metadata/einleuchtend_wrdata_2015.json
  metadata/htw_wetter_sun_2015.json
  metadata/htw_wetter_time_2015.json
  postgresql/htw_pv3_postgresql_04_function_db_log.sql
  postgresql/htw_pv3_postgresql_05_setup_tables_and_import_data.sql
Labels: documentation

#14 Correct metadata information
  metadata/einleuchtend_wrdata_2015_wr1.json
  metadata/einleuchtend_wrdata_2015_wr2.json
  metadata/einleuchtend_wrdata_2015_wr3.json
  metadata/einleuchtend_wrdata_2015_wr4.json
  metadata/htw_wetter_weatherdata_2015.json
  postgresql/htw_pv3_postgresql_05_setup_tables_and_import_data.sql
Labels: enhancement

#18 add rework to release 0.0.1
  README.md
  metadata/db_log.json
  metadata/einleuchtend_wrdata_2015_wr1.json
  metadata/einleuchtend_wrdata_2015_wr2.json
  metadata/einleuchtend_wrdata_2015_wr3.json
  metadata/einleuchtend_wrdata_2015_wr4.json
  metadata/einleuchtend_wrdata_2015_wr5.json
  metadata/htw_wetter_weatherdata_2015.json
  postgresql/htw_pv3_postgresql_04_function_db_log.sql
  postgresql/htw_pv3_postgresql_05_setup_tables_and_import_data.sql
Labels: enhancement, review

#17 Release/metadata a4 0.0.1
  README.md
  metadata/db_log.json
  metadata/einleuchtend_wrdata_2015_wr1.json
  metadata/einleuchtend_wrdata_2015_wr2.json
  metadata/einleuchtend_wrdata_2015_wr3.json
  metadata/einleuchtend_wrdata_2015_wr4.json
  metadata/einleuchtend_wrdata_2015_wr5.json
  metadata/htw_wetter_weatherdata_2015.json
  postgresql/htw_pv3_postgresql_04_function_db_log.sql
  postgresql/htw_pv3_postgresql_05_setup_tables_and_import_data.sql
Labels: review
